const blogData = [
  {
    id: 1,
    title: 'European Hyperloop Week 2023',
    desc: 'Delighted to be part of the European Hyperloop Week',
    image: 'https://utfs.io/f/O1Z0nCiJ5QIDj6DJ5ISAVEDHpXIOuMByWm1lQf6LT980xPoR',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 2,
    title: 'TRYST-IIT Delhi Conference',
    desc: 'We are thrilled to announce that Nirmaan Hyperloop had the incredible opportunity to participate in the "Know the Loop-IIT Delhi" event',
    image: 'https://utfs.io/f/O1Z0nCiJ5QIDd8YWf0H4DOMa8I9UWlQVYjyANzp0fRSLxi65',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 3,
    title: 'Pune Indian Hyperloop Committee Conference',
    desc: 'We are thrilled to announce that we recently participated in the Hyperloop Design Convention 2023',
    image: 'https://utfs.io/f/O1Z0nCiJ5QIDuW7HSyzIBOilsmRj8oDt61Kyxh7QrXW3bgTn',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 4,
    title: 'IRCTC Conference',
    desc: "The future of transportation is here and Nirmaan Hyperloop was thrilled to be a part of India's first-ever conference on Hyperloop Technology",
    image: 'https://utfs.io/f/O1Z0nCiJ5QID55BlsTN8hpJzcOvV2aFrRxX0UiImeLH1yDWo',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 5,
    title: 'Canadian Hyperloop Committee Conference',
    desc: 'Blowing minds with our aerodynamic mastery at the Canadian Hyperloop Conference',
    image: 'https://utfs.io/f/O1Z0nCiJ5QID9u1Q5eUZO1LUFQGPiZoq6uaEHlVMDt9se2NJ',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 6,
    title: 'Zephyr Exhibition',
    desc: 'Zephyr 2022 was a blast and we were thrilled to be a part of it! 🚀',
    image: 'https://utfs.io/f/O1Z0nCiJ5QIDdSonQeH4DOMa8I9UWlQVYjyANzp0fRSLxi65',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 7,
    title: 'Expo Event 2022',
    desc: 'Exciting times at the Expo Event 2022 where we discussed about our Hyperloop prototype to the best automation companies that participated in exhibition from across India! ',
    image: 'https://utfs.io/f/O1Z0nCiJ5QIDsLWebfNtqLDFBoJ734QYU62Xg1vtAlOVGaH9',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 8,
    title: "Engineer's Day 2022",
    desc: 'Sharing our innovation and vision for the future of transportation was a blast at the Innovation Exhibition ',
    image: 'https://utfs.io/f/O1Z0nCiJ5QIDTw2fZf8SLb5Msa7pjP9AmlI8Vwno2dFeRCrT',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 9,
    title: 'VJTI-IEEE Conference',
    desc: 'Our team had a great time at the @ieeevjti Exhibition, sharing our progress and exchanging ideas with fellow innovators.',
    image: 'https://utfs.io/f/O1Z0nCiJ5QID0mrUP5aFtLuTUqzgEBW9jMrsGPvbAaoZdcN8',
    date: '2015-03-25',
    location: 'Mumbai',
  },
  {
    id: 10,
    title: 'European Hyperloop Week 2022 ',
    desc: 'Thrilled to have participated in the @europeanhyperloopweek European Hyperloop Week!',
    image: 'https://utfs.io/f/O1Z0nCiJ5QID0mrUP5aFtLuTUqzgEBW9jMrsGPvbAaoZdcN8',
    date: '2015-03-25',
    location: 'Mumbai',
  },
];

export default blogData;
